syntax = "proto3";

option csharp_namespace = "Common.Protos";

import "google/protobuf/wrappers.proto";
import "google/protobuf/timestamp.proto";

package admin;

service AdminGrpcService {
  rpc GetSeatInformation (GetSeatInformationRequest) returns (GetSeatInformationResponse);
}

message GetSeatInformationRequest {
  string seatId = 1;
}

message TrainFullInformation {
  string trainName = 1;
}

message TrainCarFullInformation {
  int32 carNumber = 1;
  int32 seatType = 3;
  TrainFullInformation train = 5;
}

message GetSeatInformationResponse {
  TrainCarFullInformation trainCar = 1;
  int32 seatNumber = 2;
  int32 status = 3;
}
