syntax = "proto3";

option csharp_namespace = "Common.Protos";

import "google/protobuf/wrappers.proto";
import "google/protobuf/timestamp.proto";

package booking;

service BookingGrpcService {
  rpc BatchCheckSeatStatus (BatchCheckSeatStatusRequest) returns (BatchCheckSeatStatusResponse);
  rpc GetTicketPrice (GetTicketPriceRequest) returns (GetTicketPriceResponse);
  rpc GetTicketInformation (GetTicketInformationRequest) returns (GetTicketInformationResponses);
}

message BatchCheckSeatStatusRequest {
  repeated string seatIds = 1;
  string scheduleId = 2;
  google.protobuf.Timestamp journeyDate = 3;
}

message BatchCheckSeatStatusResponse {
  map<string, bool> seatStatuses = 1;
}

message GetTicketPriceRequest {
  string bookingOrderId = 1;
}

message GetTicketPriceResponse {
  double price = 1;
}

message GetTicketInformationRequest {
  string bookingOrderId = 1;
}

message GetTicketInformationResponses {
  repeated TicketInformation tickets = 1;
}

message TicketInformation {
  string id = 1;
  string ticketNumber = 2;
  google.protobuf.StringValue passengerId = 3;
  string trainId = 4;
  repeated string seatIds = 5;
  string trainScheduleId = 6;
  google.protobuf.Timestamp bookingDate = 7;
  google.protobuf.Timestamp journeyDate = 8;
  google.protobuf.DoubleValue totalPrice = 9;
  int32 status = 10;
  google.protobuf.StringValue remarks = 11;
  repeated PassengerInfo passengerDetails = 12;
}

message PassengerInfo {
  string id = 1;
  google.protobuf.BoolValue isMainPassenger = 2;
  int32 ageGroup = 3;
  string ticketId = 4;
  google.protobuf.StringValue firstName = 5;
  google.protobuf.StringValue lastName = 6;
  google.protobuf.Timestamp dateOfBirth = 7;
  google.protobuf.StringValue email = 8;
  google.protobuf.StringValue phoneNumber = 9;
  google.protobuf.StringValue identityNumber = 10;
}
