// <auto-generated />
using System;
using Booking.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20250524132300_NullableForPassengerInTicketSeat")]
    partial class NullableForPassengerInTicketSeat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Booking.Domain.Entities.PassengerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsMainPassenger")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_PassengerInfos_Email");

                    b.HasIndex("IdentityNumber")
                        .HasDatabaseName("IX_PassengerInfos_IdentityNumber");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_PassengerInfos_TicketId");

                    b.ToTable("PassengerInfos");
                });

            modelBuilder.Entity("Booking.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("JourneyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("PassengerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TrainScheduleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("JourneyDate")
                        .HasDatabaseName("IX_Tickets_JourneyDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Tickets_Status");

                    b.HasIndex("TicketNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Tickets_TicketNumber");

                    b.HasIndex("TrainScheduleId")
                        .HasDatabaseName("IX_Tickets_TrainScheduleId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Booking.Domain.Entities.TicketSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("PassengerInfoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PassengerInfoId")
                        .IsUnique()
                        .HasDatabaseName("IX_TicketSeats_PassengerInfoId");

                    b.HasIndex("SeatId")
                        .HasDatabaseName("IX_TicketSeats_SeatId");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_TicketSeats_TicketId");

                    b.HasIndex("TicketId", "SeatId")
                        .IsUnique()
                        .HasDatabaseName("IX_TicketSeats_TicketId_SeatId");

                    b.ToTable("TicketSeats");
                });

            modelBuilder.Entity("Booking.Domain.Entities.PassengerInfo", b =>
                {
                    b.HasOne("Booking.Domain.Entities.Ticket", "Ticket")
                        .WithMany("PassengerDetails")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Booking.Domain.Entities.TicketSeat", b =>
                {
                    b.HasOne("Booking.Domain.Entities.PassengerInfo", "PassengerInfo")
                        .WithOne("TicketSeat")
                        .HasForeignKey("Booking.Domain.Entities.TicketSeat", "PassengerInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Booking.Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketSeats")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PassengerInfo");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Booking.Domain.Entities.PassengerInfo", b =>
                {
                    b.Navigation("TicketSeat")
                        .IsRequired();
                });

            modelBuilder.Entity("Booking.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("PassengerDetails");

                    b.Navigation("TicketSeats");
                });
#pragma warning restore 612, 618
        }
    }
}
