<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0b32b905-2d6c-4469-aab8-0398b663c2b1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.OpenApi.Readers" Version="1.6.23" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\RailwayExpressVN.ServiceDefaults\RailwayExpressVN.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Common\Common.API\Common.API.csproj" />
    <ProjectReference Include="..\..\Common\Common.Application\Common.Application.csproj" />
  </ItemGroup>

</Project>
