syntax = "proto3";

option csharp_namespace = "Passenger.Grpc";

package passenger;

service PassengerService {
    rpc AddPassenger(AddPassengerRequest) returns (google.protobuf.Empty);
    rpc GetPassengerById(GetPassengerByIdRequest) returns (PassengerResponse);
    rpc GetPassengerByEmail(GetPassengerByEmailRequest) returns (PassengerResponse);
}

message AddPassengerRequest {
    string full_name = 1;
    string email = 2;
    string phone_number = 3;
    string address = 4;
}

message GetPassengerByIdRequest {
    string id = 1;
}

message GetPassengerByEmailRequest {
    string email = 1;
}

message PassengerResponse {
    string id = 1;
    string full_name = 2;
    string email = 3;
    string phone_number = 4;
    string address = 5;
}
