// <auto-generated />
using System;
using Admin.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Admin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdminContext))]
    [Migration("20250524153923_IndexingForAdminService")]
    partial class IndexingForAdminService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Admin.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainCarId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TrainCarId")
                        .HasDatabaseName("IX_Seats_TrainCarId");

                    b.HasIndex("TrainCarId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Seats_TrainCarId_SeatNumber");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Admin.Domain.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KilometricPoint")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StationOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CityName")
                        .HasDatabaseName("IX_Stations_CityName");

                    b.HasIndex("StationName")
                        .HasDatabaseName("IX_Stations_StationName");

                    b.HasIndex("StationOrder")
                        .HasDatabaseName("IX_Stations_StationOrder");

                    b.HasIndex("CityName", "StationName")
                        .HasDatabaseName("IX_Stations_CityName_StationName");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Admin.Domain.Entities.Train", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Track")
                        .HasColumnType("int");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Track")
                        .HasDatabaseName("IX_Trains_Track");

                    b.HasIndex("TrainName")
                        .HasDatabaseName("IX_Trains_TrainName");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Admin.Domain.Entities.TrainCar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("CarNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("SeatType")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SeatType")
                        .HasDatabaseName("IX_TrainCars_SeatType");

                    b.HasIndex("TrainId")
                        .HasDatabaseName("IX_TrainCars_TrainId");

                    b.HasIndex("TrainId", "CarNumber")
                        .HasDatabaseName("IX_TrainCars_TrainId_CarNumber");

                    b.ToTable("TrainCars");
                });

            modelBuilder.Entity("Admin.Domain.Entities.TrainSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArrivalStationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartureStationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<bool>("IsReturnTrip")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalStationId")
                        .HasDatabaseName("IX_TrainSchedules_ArrivalStationId");

                    b.HasIndex("ArrivalTime")
                        .HasDatabaseName("IX_TrainSchedules_ArrivalTime");

                    b.HasIndex("DepartureStationId")
                        .HasDatabaseName("IX_TrainSchedules_DepartureStationId");

                    b.HasIndex("DepartureTime")
                        .HasDatabaseName("IX_TrainSchedules_DepartureTime");

                    b.HasIndex("IsReturnTrip")
                        .HasDatabaseName("IX_TrainSchedules_IsReturnTrip");

                    b.HasIndex("TrainId")
                        .HasDatabaseName("IX_TrainSchedules_TrainId");

                    b.HasIndex("ArrivalStationId", "ArrivalTime")
                        .HasDatabaseName("IX_TrainSchedules_ArrivalStationId_ArrivalTime");

                    b.HasIndex("DepartureStationId", "ArrivalStationId")
                        .HasDatabaseName("IX_TrainSchedules_DepartureStationId_ArrivalStationId");

                    b.HasIndex("DepartureStationId", "DepartureTime", "IsReturnTrip")
                        .HasDatabaseName("IX_TrainSchedules_DepartureStationId_DepartureTime_IsReturnTrip");

                    b.ToTable("TrainSchedules");
                });

            modelBuilder.Entity("Admin.Domain.Entities.TrainStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("StationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("StationId1")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TrainId1")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("IX_TrainStatuses_StationId");

                    b.HasIndex("StationId1");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TrainStatuses_Status");

                    b.HasIndex("TrainId")
                        .HasDatabaseName("IX_TrainStatuses_TrainId");

                    b.HasIndex("TrainId1")
                        .IsUnique();

                    b.HasIndex("StationId", "Status")
                        .HasDatabaseName("IX_TrainStatuses_StationId_Status");

                    b.HasIndex("TrainId", "StationId")
                        .HasDatabaseName("IX_TrainStatuses_TrainId_StationId");

                    b.ToTable("TrainStatuses");
                });

            modelBuilder.Entity("Admin.Domain.Entities.Seat", b =>
                {
                    b.HasOne("Admin.Domain.Entities.TrainCar", "TrainCar")
                        .WithMany("Seats")
                        .HasForeignKey("TrainCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainCar");
                });

            modelBuilder.Entity("Admin.Domain.Entities.TrainCar", b =>
                {
                    b.HasOne("Admin.Domain.Entities.Train", "Train")
                        .WithMany("TrainCars")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Admin.Domain.Entities.TrainSchedule", b =>
                {
                    b.HasOne("Admin.Domain.Entities.Station", "ArrivalStation")
                        .WithMany("ArrivalTrainSchedules")
                        .HasForeignKey("ArrivalStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Admin.Domain.Entities.Station", "DepartureStation")
                        .WithMany("DepartureTrainSchedules")
                        .HasForeignKey("DepartureStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Admin.Domain.Entities.Train", "Train")
                        .WithMany("TrainSchedules")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArrivalStation");

                    b.Navigation("DepartureStation");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Admin.Domain.Entities.TrainStatus", b =>
                {
                    b.HasOne("Admin.Domain.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Admin.Domain.Entities.Station", null)
                        .WithMany("TrainAtStation")
                        .HasForeignKey("StationId1");

                    b.HasOne("Admin.Domain.Entities.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Admin.Domain.Entities.Train", null)
                        .WithOne("Status")
                        .HasForeignKey("Admin.Domain.Entities.TrainStatus", "TrainId1");

                    b.Navigation("Station");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Admin.Domain.Entities.Station", b =>
                {
                    b.Navigation("ArrivalTrainSchedules");

                    b.Navigation("DepartureTrainSchedules");

                    b.Navigation("TrainAtStation");
                });

            modelBuilder.Entity("Admin.Domain.Entities.Train", b =>
                {
                    b.Navigation("Status");

                    b.Navigation("TrainCars");

                    b.Navigation("TrainSchedules");
                });

            modelBuilder.Entity("Admin.Domain.Entities.TrainCar", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
